### ISSUE TITLE
load DICOM series over http

### ISSUE THREAD

**Issue by JustinTQ** [mix3d/vue-vtkjs-viewport#9]
Hi, How can I load a DICOM series over HTTP in MPRManager page?

**Comment by laoniu2020** [comment]
Hi, is there any update? Thanks

**Comment by mix3d** [comment]
I would start by looking at the DicomLoader example, which loads Dicoms from a file-picker interface. 
In production applications, I have been using the `cornerstone.js` loadImage function (because our normal image viewer employs cornerstone tools for dicom viewing), but if you are solely using vtk.js for dicom data, their official recommendation is to use itk.js

https://github.com/Kitware/vtk-js/issues/678

Once you have a vtk volume created, you can pass it into the MPR Manager.
